import ToggleDarkMode from "./component/ToggleDarkMode";
import {CountriesProvider} from "./context";
import "./globals.css";
export const metadata = {
  title: "Counties List",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" bg-background-light dark:bg-background-dark">
        <ToggleDarkMode />
        <div className="desktop:container mobile:mx-auto">
          <CountriesProvider>{children}</CountriesProvider>
        </div>
      </body>
    </html>
  );
}
